package com.salkcoding.oswl.vdb;

import com.fasterxml.jackson.databind.node.ObjectNode;

/** Shared provider notices for CLI and scan-derived bundles; not a rights approval registry. */
public final class BundleDataNotices {
    private BundleDataNotices() {}

    public static void addEpss(ObjectNode notices) {
        ObjectNode epss = notices.putObject("epss");
        epss.put("attribution", "EPSS: FIRST EPSS Special Interest Group; scores generated by Empirical Security.");
        epss.put("sourceUrl", "https://www.first.org/epss/");
        epss.put("dataUrl", "https://www.first.org/epss/data");
        epss.put("faqUrl", "https://www.first.org/epss/faq");
        epss.put("termsUrl", "https://www.first.org/about/policies/terms");
        epss.put("rightsStatus", "unreviewed");
        epss.put("scope", "EPSS score records only, not training data or other vulnerability sources. "
                + "Attribution does not establish redistribution permission for this bundle or its deployment.");
        epss.put("changes", "Selected CVE identifiers and probability scores are normalized into JSONL; "
                + "percentiles and other source fields may be omitted. This is not an original provider file.");
    }
}
