-- Slack/Teams incoming webhook notification settings and delivery history.
-- Used for ddl-auto=validate; Flyway applies the same statements in V14.

create table webhook_settings (
    id bigint generated by default as identity,
    provider varchar(20) not null,
    webhook_url varchar(1000),
    enabled boolean not null,
    notify_new_cve boolean not null,
    notify_gate_failure boolean not null,
    notify_scan_failure boolean not null,
    notify_waiver_expiry boolean not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table webhook_deliveries (
    id bigint generated by default as identity,
    event_type varchar(30) not null,
    project_id bigint,
    project_name varchar(160),
    reference_id varchar(40),
    status varchar(20) not null,
    http_status integer,
    error_message varchar(500),
    retry_count integer not null,
    payload_summary varchar(500),
    created_at timestamp(6) not null,
    primary key (id)
);

create index idx_webhook_deliveries_created_at on webhook_deliveries (created_at desc);
create index idx_webhook_deliveries_status on webhook_deliveries (status);
create index idx_webhook_deliveries_event_type on webhook_deliveries (event_type);
