-- OsWL full schema baseline (PostgreSQL).
--
-- Why V1 exists: production runs `ddl-auto: validate`, so Hibernate never creates tables there —
-- Flyway does. The migration set previously started at V2, which only contains incremental ALTERs
-- against an already-populated schema, so a brand-new PostgreSQL database had no way to get a
-- schema at all (V2's `ALTER TABLE libraries ...` fails when `libraries` does not exist). This
-- file closes that hole.
--
-- How it interacts with the rest of the chain (`baseline-on-migrate: true`, `baseline-version: 1`):
--   * Brand-new/empty database  -> V1 runs and creates everything, then V2-V7 apply. Every V2-V7
--     statement is guarded with IF NOT EXISTS, so they are no-ops on a schema V1 already built.
--   * Existing database (schema previously created by ddl-auto) -> Flyway baselines it at V1,
--     which marks V1 as already applied WITHOUT running it, then applies V2+ forward. This file
--     is therefore never executed against an existing deployment.
--
-- Generated from the JPA entities via `./gradlew generateSchemaBaseline`
-- (src/local/java/.../SchemaBaselineGenerator.java) and verified column-for-column against the
-- schema `ddl-auto: update` produces: 27 tables / 244 columns, exact match in both directions.
-- Regenerate rather than hand-editing when the entity model changes.
--
-- Two deliberate edits to the generated output:
--   1. Hibernate's enum CHECK constraints were dropped. `validate` does not check them, the
--      H2 dev database has none (so keeping them would make production stricter than dev), and
--      they would turn every future enum addition into a forced migration — v1.0.4 alone added
--      5 Permission values. Enum validity is enforced in the application layer by @Enumerated.
--   2. Hibernate's generated FK constraint hashes were renamed to fk_<table>_<column>.

create table ai_daily_usage (
    id bigint generated by default as identity,
    call_count integer not null,
    completion_tokens bigint not null,
    estimated_cost_usd numeric(14,6) not null,
    prompt_tokens bigint not null,
    provider varchar(32) not null,
    total_tokens bigint not null,
    usage_date date not null,
    primary key (id),
    constraint uq_ai_daily_usage unique (usage_date, provider)
);

create table ai_preferences (
    id bigint not null,
    cve_limit integer not null,
    cve_severities varchar(50) not null,
    daily_call_cap integer not null,
    default_deployment_profile varchar(40) not null,
    embedded_dir varchar(512),
    embedded_model varchar(255),
    license_limit integer not null,
    max_tokens integer,
    prompt_overrides TEXT,
    prompts_locale varchar(10) not null,
    temperature float(53),
    updated_at timestamp(6),
    primary key (id)
);

create table ai_settings (
    id bigint generated by default as identity,
    is_active boolean not null,
    api_key varchar(1000),
    base_url varchar(300),
    created_at timestamp(6),
    model_name varchar(100),
    provider VARCHAR(20) not null,
    updated_at timestamp(6),
    primary key (id)
);

create table ai_usage_events (
    id bigint generated by default as identity,
    branch varchar(160),
    completion_tokens integer not null,
    created_at timestamp(6) not null,
    estimated_cost_usd numeric(12,6) not null,
    model_name varchar(128),
    operation varchar(64) not null,
    project_name varchar(160),
    prompt_tokens integer not null,
    provider varchar(32) not null,
    total_tokens integer not null,
    usage_date date not null,
    primary key (id)
);

create table airgapped_snapshot_entries (
    id bigint generated by default as identity,
    entry_key varchar(600) not null,
    payload TEXT not null,
    source varchar(20) not null,
    primary key (id),
    constraint uq_snapshot_entry_source_key unique (source, entry_key)
);

create table airgapped_snapshot_meta (
    source varchar(20) not null,
    built_at timestamp(6),
    bundle_id varchar(64),
    format_version integer,
    imported_at timestamp(6) not null,
    origin varchar(100),
    record_count bigint not null,
    source_as_of date,
    primary key (source)
);

create table api_keys (
    id bigint generated by default as identity,
    is_active boolean not null,
    created_at timestamp(6),
    expires_at timestamp(6),
    label varchar(200),
    last_used_at timestamp(6),
    revoked_at timestamp(6),
    token_hash varchar(100) not null,
    token_prefix varchar(20) not null unique,
    project_id bigint not null,
    primary key (id)
);

create table audit_logs (
    id bigint generated by default as identity,
    action varchar(64) not null,
    actor_display_name varchar(100),
    actor_email varchar(255),
    actor_ip varchar(45),
    actor_user_id bigint,
    created_at timestamp(6) not null,
    detail TEXT,
    target_id varchar(128),
    target_name varchar(255),
    target_type varchar(64),
    primary key (id)
);

create table cache_settings (
    cache_key varchar(64) not null,
    last_cleared_at timestamp(6),
    last_cleared_by bigint,
    ttl_seconds bigint not null,
    primary key (cache_key)
);

create table cve_alerts (
    id bigint generated by default as identity,
    acknowledged boolean not null,
    acknowledged_at timestamp(6),
    cve_id varchar(30),
    detected_at timestamp(6) not null,
    ecosystem varchar(20),
    fix_version varchar(100),
    library_name varchar(300) not null,
    library_version varchar(100),
    notified boolean not null,
    notified_at timestamp(6),
    severity varchar(10),
    summary TEXT,
    vuln_id varchar(40) not null,
    library_id bigint not null,
    project_id bigint not null,
    primary key (id),
    constraint uq_cve_alerts_project_library_vuln unique (project_id, library_id, vuln_id)
);

create table dependency_paths (
    id bigint generated by default as identity,
    depth integer not null,
    path_index integer not null,
    path_nodes TEXT not null,
    scan_component_id bigint not null,
    primary key (id)
);

create table instance_setup_lock (
    id bigint not null,
    completed_at timestamp(6) with time zone not null,
    primary key (id)
);

create table jira_settings (
    id bigint generated by default as identity,
    api_token varchar(1000),
    base_url varchar(300),
    email varchar(255),
    enabled boolean not null,
    issue_type varchar(50),
    project_key varchar(50),
    updated_at timestamp(6),
    primary key (id)
);

create table libraries (
    id bigint generated by default as identity,
    ai_license_context_hash varchar(64),
    ai_license_summary TEXT,
    deprecated varchar(500),
    description TEXT,
    ecosystem varchar(20) not null,
    fetched_at timestamp(6),
    homepage varchar(500),
    is_latest_version boolean,
    latest_version varchar(100),
    license_expression_raw TEXT,
    license_name varchar(200),
    license_status varchar(20),
    malicious boolean default false not null,
    name varchar(300) not null,
    scorecard_score float(53),
    source_repo_url varchar(500),
    typosquat_reason varchar(300),
    typosquat_risk boolean default false not null,
    version varchar(100),
    version_meta_fetched_at timestamp(6),
    primary key (id),
    constraint uq_library_name_version_ecosystem unique (name, version, ecosystem)
);

create table library_cves (
    id bigint generated by default as identity,
    ai_context_hash varchar(64),
    ai_priority varchar(10),
    ai_recommended_action TEXT,
    ai_summary TEXT,
    cve_id varchar(30),
    cvss3_vector varchar(200),
    cvss_score float(53),
    cwe_id varchar(30),
    epss_score float(53),
    fix_version varchar(100),
    ghsa_id varchar(40),
    kev_listed boolean,
    severity varchar(10),
    summary TEXT,
    title varchar(300),
    library_id bigint not null,
    primary key (id)
);

create table license_policy_entries (
    id bigint generated by default as identity,
    built_in boolean not null,
    reason varchar(500),
    spdx_id varchar(100) not null unique,
    status varchar(20) not null,
    primary key (id)
);

create table project_members (
    id bigint generated by default as identity,
    created_at timestamp(6),
    role varchar(20) not null,
    user_id bigint not null,
    project_id bigint not null,
    primary key (id),
    constraint uq_project_members_project_user unique (project_id, user_id)
);

create table project_versions (
    id bigint generated by default as identity,
    branch varchar(255) not null,
    import_source varchar(10) not null,
    version_number integer not null,
    project_id bigint not null,
    primary key (id),
    constraint uq_project_version_branch unique (project_id, branch)
);

create table projects (
    id bigint generated by default as identity,
    created_at timestamp(6),
    created_by_user_id bigint,
    deleted_at timestamp(6),
    deployment_profile varchar(40),
    github_repo varchar(300),
    imported_at timestamp(6),
    latest_branch varchar(255),
    name varchar(200) not null,
    project_uuid varchar(36) unique,
    vcs_provider varchar(32),
    primary key (id),
    constraint uq_projects_github_repo unique (github_repo)
);

create table role_template_permissions (
    role_template_id bigint not null,
    permission varchar(64) not null,
    primary key (role_template_id, permission)
);

create table role_templates (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    description TEXT,
    is_built_in boolean not null,
    name varchar(100) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint uq_role_templates_name unique (name)
);

create table scan_components (
    id bigint generated by default as identity,
    deferral_expired_at timestamp(6),
    deferral_expires_at timestamp(6),
    deferral_note TEXT,
    deferral_reason varchar(50),
    deferred_at timestamp(6),
    deferred_by_name varchar(100),
    dependency_info varchar(300),
    ignored boolean not null,
    jira_issue_key varchar(50),
    jira_issue_url varchar(500),
    reviewed boolean not null,
    reviewed_by_name varchar(100),
    scope varchar(20),
    library_id bigint not null,
    scan_result_id bigint not null,
    primary key (id)
);

create table scan_results (
    id bigint generated by default as identity,
    ai_locale varchar(16),
    ai_status varchar(20),
    error_message TEXT,
    license_ai_insight TEXT,
    scanned_at timestamp(6),
    security_ai_insight TEXT,
    security_posture_insight TEXT,
    status varchar(20) not null,
    version varchar(50),
    version_diff_ai_insight TEXT,
    version_diff_from_scan_id bigint,
    project_id bigint not null,
    primary key (id)
);

create table security_settings (
    id bigint not null,
    mail_encryption varchar(20),
    mail_host varchar(255),
    mail_mode varchar(20) not null,
    mail_password varchar(1000),
    mail_port integer,
    mail_sender_address varchar(255),
    mail_sender_name varchar(100),
    mail_username varchar(255),
    min_password_length integer not null,
    two_fa_mode varchar(20) not null,
    updated_at timestamp(6),
    primary key (id)
);

create table user_role_assignments (
    user_id bigint not null,
    role_template_id bigint not null,
    primary key (user_id, role_template_id)
);

create table user_vcs_connections (
    id bigint generated by default as identity,
    access_token_encrypted TEXT not null,
    active boolean not null,
    created_at timestamp(6) not null,
    provider varchar(32) not null,
    server_url varchar(500),
    updated_at timestamp(6) not null,
    vcs_username varchar(200),
    user_id bigint not null,
    primary key (id)
);

create table users (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    display_name varchar(100) not null,
    email varchar(255) not null,
    enabled boolean not null,
    is_system_admin boolean not null,
    last_login_at timestamp(6),
    login_failure_count integer not null,
    must_change_password boolean not null,
    password_hash varchar(255) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint uq_users_email unique (email)
);

create index ix_ai_usage_events_date_provider
   on ai_usage_events (usage_date, provider);

create index ix_ai_usage_events_date_created
   on ai_usage_events (usage_date, created_at);

create index idx_snapshot_entries_source_key
   on airgapped_snapshot_entries (source, entry_key);

create index ix_audit_logs_created_at
   on audit_logs (created_at);

create index ix_audit_logs_actor_user_id
   on audit_logs (actor_user_id);

create index idx_cve_alerts_project_ack
   on cve_alerts (project_id, acknowledged);

create index idx_dep_paths_scan_comp
   on dependency_paths (scan_component_id);

create index idx_libraries_name_version
   on libraries (name, version);

create index idx_library_cves_library
   on library_cves (library_id);

create index idx_library_cves_cve_id
   on library_cves (cve_id);

create index idx_project_members_user_id
   on project_members (user_id);

create index idx_scan_components_scan
   on scan_components (scan_result_id);

create index idx_scan_components_library
   on scan_components (library_id);

alter table if exists api_keys
   add constraint fk_api_keys_project_id
   foreign key (project_id)
   references projects;

alter table if exists cve_alerts
   add constraint fk_cve_alerts_library_id
   foreign key (library_id)
   references libraries;

alter table if exists cve_alerts
   add constraint fk_cve_alerts_project_id
   foreign key (project_id)
   references projects;

alter table if exists dependency_paths
   add constraint fk_dependency_paths_scan_component_id
   foreign key (scan_component_id)
   references scan_components;

alter table if exists library_cves
   add constraint fk_library_cves_library_id
   foreign key (library_id)
   references libraries;

alter table if exists project_members
   add constraint fk_project_members_project_id
   foreign key (project_id)
   references projects;

alter table if exists project_versions
   add constraint fk_project_versions_project_id
   foreign key (project_id)
   references projects;

alter table if exists role_template_permissions
   add constraint fk_role_template_permissions_role_template_id
   foreign key (role_template_id)
   references role_templates;

alter table if exists scan_components
   add constraint fk_scan_components_library_id
   foreign key (library_id)
   references libraries;

alter table if exists scan_components
   add constraint fk_scan_components_scan_result_id
   foreign key (scan_result_id)
   references scan_results;

alter table if exists scan_results
   add constraint fk_scan_results_project_id
   foreign key (project_id)
   references projects;

alter table if exists user_role_assignments
   add constraint fk_user_role_assignments_role_template_id
   foreign key (role_template_id)
   references role_templates;

alter table if exists user_role_assignments
   add constraint fk_user_role_assignments_user_id
   foreign key (user_id)
   references users;

alter table if exists user_vcs_connections
   add constraint fk_user_vcs_connections_user_id
   foreign key (user_id)
   references users;
