-- Secret and IaC misconfiguration findings from Quick Import clones.
-- The matched secret value itself is never stored — only location, rule id and a hash fingerprint.
create table scan_findings (
    id bigint generated by default as identity primary key,
    scan_result_id bigint not null references scan_results(id) on delete cascade,
    type varchar(10) not null,
    rule_id varchar(100) not null,
    severity varchar(10) not null,
    file_path varchar(1000) not null,
    line_number integer,
    description varchar(500) not null,
    fingerprint varchar(12),
    created_at timestamp not null default current_timestamp
);

create index idx_scan_findings_scan_result on scan_findings(scan_result_id);
create index idx_scan_findings_scan_result_type on scan_findings(scan_result_id, type);
