-- Named Security Center filter/sort combinations, scoped per project.
create table saved_views (
    id bigint generated by default as identity,
    project_id bigint not null,
    created_by_user_id bigint not null,
    created_by_name varchar(150) not null,
    name varchar(100) not null,
    filters_json text not null,
    shared boolean not null default false,
    created_at timestamp not null,
    primary key (id)
);

create index idx_saved_views_project_id on saved_views (project_id);

alter table if exists saved_views
   add constraint fk_saved_views_project_id
   foreign key (project_id)
   references projects;
