-- Single-row branding settings applied to printable reports (logo, company name, header, cover page).
create table report_branding_settings (
    id bigint generated by default as identity,
    company_name varchar(150),
    logo_data_uri text,
    header_text varchar(300),
    show_cover_page boolean not null default false,
    updated_at timestamp,
    primary key (id)
);
