CREATE TABLE IF NOT EXISTS import_coordinator (id BIGINT PRIMARY KEY);
INSERT INTO import_coordinator (id) SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM import_coordinator WHERE id = 1);
CREATE TABLE IF NOT EXISTS import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL UNIQUE,
    owner_id BIGINT NOT NULL,
    repo_key VARCHAR(64) NOT NULL,
    worker_id VARCHAR(36) NOT NULL,
    phase VARCHAR(20) NOT NULL,
    snapshot_json TEXT NOT NULL,
    lease_until TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    canceled BOOLEAN NOT NULL DEFAULT FALSE,
    worker_active BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_import_jobs_owner ON import_jobs(owner_id);
CREATE INDEX IF NOT EXISTS idx_import_jobs_lease ON import_jobs(lease_until);
