CREATE TABLE IF NOT EXISTS web_push_subscriptions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 endpoint_hash VARCHAR(64) NOT NULL UNIQUE,
 encrypted_subscription TEXT NOT NULL,
 expires_at TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_web_push_user ON web_push_subscriptions(user_id);
CREATE TABLE IF NOT EXISTS web_push_deliveries (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 subscription_id BIGINT NOT NULL REFERENCES web_push_subscriptions(id) ON DELETE CASCADE,
 project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
 event_key VARCHAR(100) NOT NULL,
 event_type VARCHAR(20) NOT NULL,
 attempts INTEGER NOT NULL,
 finished BOOLEAN NOT NULL,
 next_attempt TIMESTAMP NOT NULL,
 expires_at TIMESTAMP NOT NULL,
 last_status INTEGER,
 UNIQUE(subscription_id,event_key)
);
CREATE INDEX IF NOT EXISTS idx_web_push_due ON web_push_deliveries(finished,next_attempt);
