CREATE TABLE snapshot_generations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    published_at TIMESTAMP NOT NULL,
    source_metadata TEXT NOT NULL
);
CREATE TABLE snapshot_generation_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generation_id BIGINT NOT NULL REFERENCES snapshot_generations(id),
    source VARCHAR(20) NOT NULL,
    entry_key VARCHAR(600) NOT NULL,
    payload TEXT NOT NULL,
    CONSTRAINT uq_snapshot_generation_entry UNIQUE (generation_id, source, entry_key)
);
CREATE TABLE snapshot_active_generation (
    id BIGINT PRIMARY KEY,
    generation_id BIGINT REFERENCES snapshot_generations(id)
);
INSERT INTO database_mutation_locks(id) SELECT 3 WHERE NOT EXISTS (SELECT 1 FROM database_mutation_locks WHERE id=3);
