package com.salkcoding.oswl.vdb;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.zip.GZIPOutputStream;
import java.util.zip.ZipFile;
import static org.assertj.core.api.Assertions.*;

class VdbSourceSelectionTest {
    @ParameterizedTest
    @ValueSource(strings = {"github-advisory", "nvd", "unknown", ""})
    void writerCannotSilentlyOmitAnUnsupportedSelectedSource(String source, @TempDir Path directory) throws Exception {
        Path output = directory.resolve("bundle.zip");
        Files.writeString(output, "existing bundle");
        assertThatThrownBy(() -> new VdbBundleWriter(new ObjectMapper(), java.util.Set.of("osv", source)).write(
                output, java.util.Map.of(), java.time.LocalDate.now(), List.of(), List.of(), java.util.Map.of(),
                java.util.Map.of(), java.time.LocalDate.now(), java.util.Set.of(), java.time.LocalDate.now(),
                0, null, List.of(), null))
                .isInstanceOf(IllegalArgumentException.class).hasMessageContaining("Unsupported writer source");
        assertThat(Files.readString(output)).isEqualTo("existing bundle");
    }

    @ParameterizedTest
    @ValueSource(strings = {"", ",", ",,", " ", "osv,", ",osv", "osv,,kev"})
    void malformedSourceListsCannotReplaceOutput(String sources, @TempDir Path directory) throws Exception {
        Path output = directory.resolve("bundle.zip");
        Files.writeString(output, "existing bundle");
        assertThat(new VdbBuilderCli().run(new String[]{"build", "--sources", sources,
                "--offline-sources", directory.toString(), "--out", output.toString()})).isEqualTo(1);
        assertThat(Files.readString(output)).isEqualTo("existing bundle");
    }

    @ParameterizedTest
    @ValueSource(strings = {"", ",", ",,", " ", "NPM,", ",NPM", "NPM,,MAVEN"})
    void malformedEcosystemListsAreRejected(String ecosystems) {
        assertThatThrownBy(() -> VdbBuildOptions.parse(List.of("--sources", "osv", "--ecosystems", ecosystems)))
                .isInstanceOf(IllegalArgumentException.class).hasMessageContaining("--ecosystems");
    }

    @Test
    void validListsTrimWhitespaceAndRetainSelectionOrder() {
        var options = VdbBuildOptions.parse(List.of("--sources", " osv , kev,osv ", "--ecosystems", " npm, Maven,npm "));
        assertThat(options.sources()).containsExactly("osv", "kev");
        assertThat(options.ecosystems()).containsExactly("NPM", "MAVEN");
    }

    @ParameterizedTest
    @ValueSource(strings = {"github-advisory", "nvd", "osv,github-advisory", "osv,nvd"})
    void unsupportedCollectorsFailBeforeReplacingOutput(String sources, @TempDir Path directory) throws Exception {
        Path output = directory.resolve("bundle.zip");
        Files.writeString(output, "existing bundle");
        assertThat(new VdbBuilderCli().run(new String[]{"build", "--sources", sources,
                "--offline-sources", directory.toString(), "--out", output.toString()})).isEqualTo(1);
        assertThat(Files.readString(output)).isEqualTo("existing bundle");
    }

    @Test
    void defaultsOnlySelectConnectedCollectors() {
        assertThat(VdbBuildOptions.parse(List.of()).sources()).containsExactly("osv", "epss", "kev", "depsdev");
    }

    @ParameterizedTest
    @ValueSource(strings = {"--github-advisory-token", "--github-api-base", "--nvd-api-key"})
    void disconnectedCollectorOptionsAreRejected(String option) {
        assertThatThrownBy(() -> VdbBuildOptions.parse(List.of("--sources", "osv", option, "unused-value")))
                .isInstanceOf(IllegalArgumentException.class).hasMessageContaining(option);
    }

    @Test
    void epssCliBuildIncludesRequiredDataNotice(@TempDir Path directory) throws Exception {
        try (var output = new GZIPOutputStream(Files.newOutputStream(directory.resolve("epss_scores-current.csv.gz")))) {
            output.write("#score_date:2026-01-01\ncve,epss,percentile\nCVE-2026-0001,0.5,0.5\n".getBytes(StandardCharsets.UTF_8));
        }
        Path bundle = directory.resolve("bundle.zip");

        assertThat(new VdbBuilderCli().run(new String[]{"build", "--sources", "epss",
                "--offline-sources", directory.toString(), "--out", bundle.toString()})).isZero();

        JsonNode notice = readMeta(bundle).path("dataNotices").path("epss");
        assertThat(notice.path("attribution").asText()).isEqualTo(
                "EPSS: FIRST EPSS Special Interest Group; scores generated by Empirical Security.");
        assertThat(notice.path("sourceUrl").asText()).isEqualTo("https://www.first.org/epss/");
        assertThat(notice.path("dataUrl").asText()).isEqualTo("https://www.first.org/epss/data");
        assertThat(notice.path("termsUrl").asText()).isEqualTo("https://www.first.org/about/policies/terms");
        assertThat(notice.path("rightsStatus").asText()).isEqualTo("unreviewed");
        assertThat(notice.path("changes").asText()).contains("JSONL");
        assertThat(notice.has("license")).isFalse();
    }

    @Test
    void nonEpssCliBuildOmitsEpssDataNotice(@TempDir Path directory) throws Exception {
        Files.writeString(directory.resolve("kev.json"), "{\"count\":1,\"catalogVersion\":\"fixture\","
                + "\"dateReleased\":\"2020-01-01T00:00:00Z\",\"vulnerabilities\":[{"
                + "\"cveID\":\"CVE-2026-0001\"}]}" );
        Path bundle = directory.resolve("bundle.zip");

        assertThat(new VdbBuilderCli().run(new String[]{"build", "--sources", "kev",
                "--offline-sources", directory.toString(), "--out", bundle.toString()})).isZero();

        assertThat(readMeta(bundle).path("dataNotices").has("epss")).isFalse();
    }

    private static JsonNode readMeta(Path bundle) throws Exception {
        try (ZipFile zip = new ZipFile(bundle.toFile());
             InputStream input = zip.getInputStream(zip.getEntry("meta.json"))) {
            return new ObjectMapper().readTree(input);
        }
    }
}
